modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="forgottenfauna" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Forgotten Fauna" #mandatory
credits="Coda, VakyPanda" #optional
description='''Placeholder description.'''
[[dependencies.forgottenfauna]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[36,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.forgottenfauna]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
[[dependencies.forgottenfauna]]
modId="weecore"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"
